apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataops-gr
  namespace: greenroom
  labels:
    app: dataops-gr
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataops-gr
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: dataops-gr
        env: charite
    spec:
      containers:
        - name: dataops-gr
          image: 10.32.42.225:5000/dataops-gr:<VERSION>
          ports:
            - containerPort: 5063
          env:
          - name: env
            value: "charite"
          - name: RDS_PWD
            valueFrom:
              secretKeyRef:
                name: opsdb
                key: password
          readinessProbe:
            tcpSocket:
              port: 5063
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "32Gi"
              cpu: "4"
            limits:
              memory: "32Gi"
              cpu: "4"
          volumeMounts:
          - name: nfsvol
            mountPath: /data/vre-storage
          - name: nfsvol-vre-data
            mountPath: /vre-data
          - mountPath: /tmp/dataops
            name: temp-volume
      nodeSelector:
        namespace: greenroom
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: greenroom-storage
        - name: nfsvol-vre-data
          nfs:
            server: bihnas2.charite.de
            path: /AG-Ritter-VRE/VRE-namespace/vre-vre-data-pvc-ab20736f-3a07-4f3e-bfc9-5c804e6a34d4/
#          persistentVolumeClaim:
#            claimName: greenroom-vre-storage
        - name: temp-volume
          hostPath:
            path: /tmp/temp-data/dataops
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: dataops-gr
  namespace: greenroom
  labels:
    app: dataops-gr
    env: charite
spec:
  ports:
  - name: dataops-gr
    port: 5063
    targetPort: 5063
  selector:
    app: dataops-gr
    env: charite
  type: ClusterIP
